version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: paksa_financial_local
      POSTGRES_USER: paksa_user
      POSTGRES_PASSWORD: paksa_local_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paksa_user -d paksa_financial_local"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    command: redis-server --requirepass paksa_redis_2024
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    environment:
      DATABASE_URL: postgresql+asyncpg://paksa_user:paksa_local_2024@postgres:5432/paksa_financial_local
      REDIS_URL: redis://:paksa_redis_2024@redis:6379/0
      JWT_SECRET_KEY: paksa_jwt_secret_key_local_2024_super_secure
      ENVIRONMENT: local_production
      LOG_LEVEL: INFO
      CORS_ORIGINS: http://localhost:3000,http://localhost:8080
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./logs:/var/log/paksa
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    environment:
      VITE_API_BASE_URL: http://localhost:8000/api/v1
      VITE_APP_TITLE: Paksa Financial System - Local Production
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0

volumes:
  postgres_data:
  redis_data: